---
- hosts: master
  become: true
  pre_tasks: 
    - name: Bring private ip of remote server
      set_fact:
        mprivateip: "{{ ansible_eth0.ipv4.address }}"
      delegate_to: "{{ item }}"
      loop: "{{ groups.master }}"


  roles: 
    - kubernetes-setup

