---
- name: Disable SWAP
  command: "{{ item }}" 
  with_items: 
    - "sed -i '/swap/d' /etc/fstab"
    - "swapoff -a"

- name: Stop firwalld if running
  command: systemctl stop firewalld

- name: Disable SELinux 
  selinux:
    state: disabled

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644 

- name: Install Kubernets compatible Docker 
  yum: 
    name: docker-ce-18.06.1.ce-3.el7*
    state: present

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes
  register: docser
   
- debug: 
    var: "{{ docser }}"
       

- name: Create repository for kubernetes
  yum_repository: 
    name: kubernetes
    description:  kubernetes
    file: kuberepo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: yes
    enabled: yes
    repo_gpgcheck: yes
    gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"


- name: Install kubernetes base packages
  yum:   
    name: "{{ item }}"
    state: latest
  with_items: 
    - "kubelet"
    - "kubeadm"
    - "kubectl"
        
- name: Start and enable Kubelet service 
  service: 
    name: kubelet
    state: started
    enabled: yes
  register: kubeser

- debug:
    var: "{{ kubeser }}"
    
