---
- name: Initialize kubernetes cluster 
  command: "kubeadm init --apiserver-advertise-address={{ mprivateip }} --pod-network-cidr=10.244.0.0/16"
  register: initialize_clus
  ignore_errors: yes
  delegate_to: "{{ item }}"
  with_items: "{{ groups['master'] }}"

- debug:   
    var: "{{ initialize_clus }}"



